### ISSUE TITLE
Conditionally disable listener or change guessers

### ISSUE THREAD

**Issue by jaymecd** [lunetics/LocaleBundle#107]
I've noticed one limitation during developing REST API for the project.
Default configuration is:

```
lunetics_locale:
    strict_mode: true
    allowed_locales: %conf_locale_available%
    guessing_order:
        - router
        - cookie
        - browser
    cookie:
        set_on_change: true
```

For the website it completely fine, great job.
But for stateless API I see 2 issues:
1) it tries to detect locale which potentially could lead to unexpected behaviour with locale dependent output 
2) sets client cookie with detected locale

Most preferable way would be to conditionally disable listener for specific routes or so, and use guesser manually, eg `QueryLocaleGuesser`, to fetch locale regarding to API specs.
