### ISSUE TITLE
Empty language switcher on 404 page

### ISSUE THREAD

**Issue by Mondane** [lunetics/LocaleBundle#114]
I have a custom 404 page which also shows the language switcher. On this page there are no entries in the switcher, is there a setting I'm missing? I would like to be able to translate this page too.

**Comment by Mondane** [comment]
Any progress on this one? The languages are there when testing the page in symfony 2.6 and higher using this in routing_dev.yml:

```yaml
_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
```

and this URL `/app_dev.php/_error/403`
