### ISSUE TITLE
Language switcher not working

### ISSUE THREAD

**Issue by jernejpangersic** [lunetics/LocaleBundle#118]
Hi,

I'm developing a multi-language site. I would like to be able to serve user's the content in their language, without changing the routes, as I don't want the locale parameter in the route. 
If I understood correctly, this can be done with your bundle.

However, I haven't been able to get it to work.
These are my settings:

```
lunetics_locale:
  guessing_order:
      - cookie
      - session
      - browser
  cookie:
    set_on_change: true
  allowed_locales:
    - en
    - sl
```

The cookie is set to SL (my browser's language). Even If I use the locale switcher, the cookie is still set to SL. It seems like the guessers ignore the order.
Thanks in advance for your help!

EDIT: Nevermind, I already solved it... Added "query" to guessers, and it works :)
