### ISSUE TITLE
The attribute "name" must be set for path "lunetics_locale.domain.locale_map"

### ISSUE THREAD

**Issue by rschaaphuizen** [lunetics/LocaleBundle#151]
I'm using version 2.4.1 and added the following config, but when i try to clear the cache I receive the error from the title.

    guessing_order:
        - domain
        - query
        - router
        - session
        - cookie
        - browser
    domain:
        locale_map:
            - xdomain.com: en_EN
            - xdomain.de: de
            - xdomain.ch: de
    cookie:
        set_on_change: true

**Comment by dbu** [comment]
symfony 2.4 is end of live and unfortunately not supported by this
bundle anymore. we should update the composer.json to conflict with
symfony 2.4. please upgrade to a newer version of symfony (or if you
can't, see if there is an older version of LocaleBundle that does not
ignore build errors for symfony 2.4 in its .travis.yml file)

**Comment by rschaaphuizen** [comment]
I've updated symfony to version 2.6.6 and uses the 2.4.1 version of this bundle. Still got the same error.

**Comment by dbu** [comment]
hm, strange. then it looks like the documentation is incorrect, or the domain configuration is broken. @lunetics ideas?
otherwise you could look at the code where the error happens (or is it inside symfony while validating the configuration?)

**Comment by rschaaphuizen** [comment]
Yeah, It's strange. Please let me know if there are any ideas. I can't figure out why it is going wrong.

**Comment by mhaeussler-magari** [comment]
For me worked the following:

```
domain:
    locale_map:
        xdomain.com: en_EN
        xdomain.de: de
        xdomain.ch: de
```

Seems like the docs are not up to date?

**Comment by skonsoft** [comment]
Hello i got the same error with Top Level domain.

```
topleveldomain:
        locale_map:
            - com: en
            - be: fr_BE
            - fr: fr
```

The errors is:
```
The attribute "name" must be set for path "lunetics_locale.topleveldomain.locale_map"
```
I followed the doc but i got this error, i looked into the code of Configuration.php class and i found this:

```
->arrayNode('topleveldomain')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('locale_map')
                        ->useAttributeAsKey('name')
                          ->prototype('scalar')->end()
                        ->end()
                    ->end()
                ->end()
```

So there is a required attribute "name" !

Can you fix this please.

Thank you

**Comment by mhaeussler-magari** [comment]
Just have a look at my comment above.
Try the following:

```
topleveldomain:
        locale_map:
            com: en
            be: fr_BE
            fr: fr
```
