### ISSUE TITLE
Translation not found. 

### ISSUE THREAD

**Issue by guillaume-ro-fr** [lunetics/LocaleBundle#168]
Hello,

In recent days, I have a problem with the lunetics_locale bundle.
Indeed, when submitting a form, a warning appears in the logs and filled completely. The messages are :

```
WARNING - Translation not found.
Context: {"id": "The local \"% string% \ "is not a valid local" "domain" "validators", "Local": "en_GB"}
WARNING - Translation not found.
Context: {"id": "The local \"% string% \ "is not allowed by application configuration.", "Domain", "validators", "Local": "en_GB"}
```

They are repeated at least 500 times by each form validation.
I'm on empty my cache.
Here is my config.yml:

``` yaml
lunetics_locale:
    allowed_locales:
        - fr
        - en
    strict_mode: false
    guessing_order:
        - session
        - cookie
        - browser
        - query
        - router
    cookie:
        set_on_change: true
    form:
        strict_mode: false
        languages_only: true
```

My piece of code in the controller :

``` php
        $user = $this->getUser();
        $oldLocale = $user->getLocale();
        $form = $this->createForm(new UserFormType(), $user);
        $form->submit($request->request->all());
        if ($form->isValid()) {
            $this->get('fos_user.user_manager')->updateUser($user);

            if ($oldLocale !== $user->getLocale()) {
                $this->get('event_dispatcher')->dispatch(LocaleBundleEvents::onLocaleChange, new FilterLocaleSwitchEvent($request, $user->getLocale()));
            }

            return $this->handleView($this->view(true, 200));
        }

        return $this->handleView($this->view($form, 400));
```

My form :

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // add your custom field
        $builder
            ->add('firstname', 'text')
            ->add('surname', 'text')
            ->add('gender', 'text')
            ->add(
                'birthday',
                'birthday',
                [
                    'widget' => 'single_text',
                    'input' => 'datetime',
                    'format' => 'yyyy-MM-dd',
                ]
            )
            ->add('locale', 'lunetics_locale')
            ->add('avatar', 'text', ['mapped' => false])
            ->remove('current_password')
            ->remove('username')
        ;
    }
```

The real problem is that during the debug, FirePHP filled headers with such information and nginx returns a 502 error.
If I use "locale" in the form instead of "lunetics_locale", I have no problem.

Any ideas ?

Thanks

PS : Sorry for my english :smile:
