### ISSUE TITLE
Compatibility with Symfony Flex

### ISSUE THREAD

**Issue by Mondane** [lunetics/LocaleBundle#207]
When I require this bundle, I get the following error:

> The child node "guessing_order" at path "lunetics_locale" must be configured.

A workaround is to add the configuration beforehand:

**config/packages/lunetics_locale.yaml**
```yaml
lunetics_locale:
    allowed_locales: '%locales%'
    guessing_order:
        - query
        - session
        - cookie
        - browser
        - router
    switcher:
        show_current_locale: true
```

But this shouldn't be necessary.
