### ISSUE TITLE
Switcher not working....

### ISSUE THREAD

**Issue by eMerzh** [lunetics/LocaleBundle#34]
Hi, 
i'm quite new to SF 2.1 so i don't know if it's me or a mis-configuration but i can't make the switcher working...

i've added the bundle to my composer.json , updated it, and added it to the appkernel.php

Then i've added to my app/config/config.yml

```
lunetics_locale:
  guessing_order:
    - cookie
    - router
    - browser
  allowed_locales: %locales%
  cookie:
    set_on_detection: true
```

with the locales defined in parameters.yml..

Then i've added to my layout.twig
    {{ locale_switcher('home_lang') }}

and in my routing.yml 

```
home_lang:
     pattern: /lang/{_locale}
     defaults:
         _controller: lunetics_locale.switcher_controller:switchAction
         _locale: %locale%
```

I clear my cookies then launch my homepage...  LocalBundle correctly take the lang from my browser, but i'm unable to use the switcher ...
When i click on the "  Switch to :    French ,   Dutch.... "  ... nothing happend ...

i got redirected  to the same page with the same locale...

what did i miss?

Thanks for your help
