### ISSUE TITLE
Locale not intercepted

### ISSUE THREAD

**Issue by lughino** [lunetics/LocaleBundle#82]
Hello,
I have a problem like this:
I have the routes set this way:

``` yaml
index_not_localized:
    path:   /
    defaults:  { _controller: "AcmeSiteBundle:Default:index", _locale: %locale% }

acme_site:
    resource: "@AcmeSiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  en|it
```

if I go to www.example.com is set to the default local and not that of the user.
I have configured this way:

``` yaml
guessing_order:
    - query
    - router
    - session
    - cookie
    - browser
```

But if imposed as this configuration:

``` yaml
guessing_order:
    - session
    - cookie
    - browser
    - query
    - router
```

even if switch to another language does not change the value of the session and cookies.
Is there a problem, or I'm wrong configuration?
How can I get what I want?
thanks
