### ISSUE TITLE
Config for JMSI18nRoutingBundle

### ISSUE THREAD

**Issue by hacfi** [lunetics/LocaleBundle#85]
Hi @lunetics,
have you ever used this bundle in combination with https://github.com/schmittjoh/JMSI18nRoutingBundle?
I was wondering which configuration is recommended. I currently have:

``` yml
lunetics_locale:
    allowed_locales: [de, en]
    guessing_order:
        - query
        - router
        - cookie
        - session
        - browser
    session:
        variable: _locale
```

It works ok but visiting `http://test.com/en/?_locale=de` will set the cookie to de but translate fields in English.
